services:
  frontend:
    container_name: frontend
    image: ghcr.io/enesefetokta/fertile-notify-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - fertile-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
    logging: &default-logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    container_name: api
    image: ghcr.io/enesefetokta/fertile-notify-api:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - OTP_LENGTH=${OTP_LENGTH}
      - OTP_EXPIRY_IN_MINUTES=${OTP_EXPIRY_IN_MINUTES}
      - SYSTEM_SMTP_HOST=${SYSTEM_SMTP_HOST}
      - SYSTEM_SMTP_PORT=${SYSTEM_SMTP_PORT}
      - SYSTEM_SMTP_USER=${SYSTEM_SMTP_USER}
      - SYSTEM_SMTP_PASS=${SYSTEM_SMTP_PASS}
      - SYSTEM_SMTP_FROM=${SYSTEM_SMTP_FROM}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - fertile-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 400M
    logging:
      <<: *default-logging

  redis:
    container_name: redis
    image: redis:7-alpine
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - fertile-network
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 80M
    logging:
      <<: *default-logging

  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - fertile-network
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 300M
    logging:
      <<: *default-logging

  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    command: >
      postgres -c shared_buffers=64MB -c effective_cache_size=128MB -c work_mem=4MB -c maintenance_work_mem=32MB
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fertile-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 300M
    logging:
      <<: *default-logging

  tunnel:
    image: cloudflare/cloudflared:latest
    profiles: [ "prod" ]
    container_name: tunnel
    command: tunnel --no-autoupdate run
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - fertile-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
    logging:
      <<: *default-logging

networks:
  fertile-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
